---
title: "FigS11_pdep_VR"
output: html_document
date: "2024-04-25"
---

```{r}
library(ggplot2)
library(patchwork)
library(dplyr)
```

```{r}
pdep_data <- readRDS("./data/VR_pdep_data.RDS")
```

```{r}
plot_data <- bind_rows(pdep_data) |> 
  mutate(VR = factor(VR,
                     levels = c("a) Female survival", "b) Male survival\n (juvenile)", "c) Male survival\n (adult)",
                                "d) Reproduction\n(primiparous)", "e) Reproduction\n(non-primiparous)", "f) Twinning\n")),
         year = focal_var,
         lower = low,
         upper = up,
         mean = pointp)

```

```{r}

bigtick_scale <- 0.0375
smalltick_scale <- 0.02

surv_ymax <- 1
surv_ymin <- 0.9

repro_ymax <- 0.25
repro_ymin <- 0

twin_ymax <- 0.8
twin_ymin <- 0

surv_panel <- ggplot(data = filter(plot_data, grepl("survival", x = VR))) +
  geom_ribbon(aes(x = year, ymin = lower, ymax = upper),
              fill = "grey85") +
  geom_line(aes(x = year, y = mean)) +
  # geom_hline(aes(yintercept = globalmean), lty = 2) +
  coord_cartesian(clip = "off",
                  expand = FALSE,
                  ylim = c(surv_ymin, surv_ymax),
                  xlim = c(1995, 2023)) +
  annotate(geom = "segment",
           y = surv_ymin, yend = surv_ymin-(surv_ymax-surv_ymin)*bigtick_scale,
           x = seq(1995, 2020, by = 5),
           xend = seq(1995, 2020, by = 5),
           lineend = "round", linejoin = "round") +
  annotate(geom = "segment",
           y = surv_ymin, yend = surv_ymin-(surv_ymax-surv_ymin)*smalltick_scale,
           x = seq(1995, 2023, by = 1),
           xend = seq(1995, 2023, by = 1),
           lineend = "round", linejoin = "round") +
  facet_wrap(facets = ~VR, scales = "free_y") +
  labs(y = "Proportion") +
  scale_y_continuous(breaks = seq(surv_ymin, surv_ymax, 0.02)) +
  scale_colour_discrete(guide = NULL) +
  theme_classic() +
  theme(axis.text = element_text(colour = "black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text = element_text(colour = "black"),
        strip.background = element_rect(linewidth = 0.5),
        panel.background = element_rect(linewidth = 0.5, colour = "black"),
        plot.margin = margin(b = 5, t = 5))

repro_panel <- ggplot(data = filter(plot_data, grepl("Repro", x = VR))) +
  geom_ribbon(aes(x = year, ymin = lower, ymax = upper),
              fill = "grey85") +
  geom_line(aes(x = year, y = mean)) +
  # geom_hline(aes(yintercept = globalmean), lty = 2) +
  coord_cartesian(clip = "off",
                  expand = FALSE,
                  ylim = c(repro_ymin, repro_ymax),
                  xlim = c(1995, 2023)) +
  annotate(geom = "segment",
           y = repro_ymin, yend = repro_ymin-(repro_ymax-repro_ymin)*bigtick_scale,
           x = seq(1995, 2020, by = 5),
           xend = seq(1995, 2020, by = 5),
           lineend = "round", linejoin = "round") +
  annotate(geom = "segment",
           y = repro_ymin, yend = repro_ymin-(repro_ymax-repro_ymin)*smalltick_scale,
           x = seq(1995, 2023, by = 1),
           xend = seq(1995, 2023, by = 1),
           lineend = "round", linejoin = "round") +
  labs(y = "Proportion") +
  scale_y_continuous(breaks = seq(0, repro_ymax, 0.04)) +
  facet_wrap(facets = ~VR, scales = "free_y") +
  scale_colour_discrete(guide = NULL) +
  theme_classic() +
  theme(axis.text = element_text(colour = "black"),
        axis.text.x = element_text(margin = margin(t = 4)),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text = element_text(colour = "black"),
        panel.background = element_rect(linewidth = 0.5, colour = "black"),
        strip.background = element_rect(linewidth = 0.5))

twin_panel <- ggplot(data = filter(plot_data, grepl("Twin", x = VR))) +
  geom_ribbon(aes(x = year, ymin = lower, ymax = upper),
              fill = "grey85") +
  geom_line(aes(x = year, y = mean)) +
  # geom_hline(aes(yintercept = globalmean), lty = 2) +
  coord_cartesian(clip = "off",
                  expand = FALSE,
                  ylim = c(twin_ymin, twin_ymax),
                  xlim = c(1995, 2023)) +
  annotate(geom = "segment",
           y = twin_ymin, yend = twin_ymin-(twin_ymax-twin_ymin)*bigtick_scale,
           x = seq(1995, 2020, by = 5),
           xend = seq(1995, 2020, by = 5),
           lineend = "round", linejoin = "round") +
  annotate(geom = "segment",
           y = twin_ymin, yend = twin_ymin-(twin_ymax-twin_ymin)*smalltick_scale,
           x = seq(1995, 2023, by = 1),
           xend = seq(1995, 2023, by = 1),
           lineend = "round", linejoin = "round") +
  scale_y_continuous(breaks = seq(0, 0.8, 0.1),
                     labels = format(seq(0, 0.8, 0.1), nsmall = 2)) +
  facet_wrap(facets = ~VR, scales = "free_y") +
  scale_colour_discrete(guide = NULL) +
  theme_classic() +
  theme(axis.text = element_text(colour = "black"),
        axis.text.x = element_text(margin = margin(t = 4)),
        axis.title = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text = element_text(colour = "black"),
        strip.background = element_rect(linewidth = 0.5),
        panel.background = element_rect(linewidth = 0.5, colour = "black"),
        plot.margin = margin(b = 5, t = 5))

surv_panel/((repro_panel|twin_panel) + plot_layout(widths = c(2.2, 1)))

ggsave(filename = here::here("./plots/pdep_VR.png"), dpi = 600,
       width = 8, height = 5)
```
