---
title: "elasticity_oddsratio"
output: html_document
date: "2023-03-24"
---

```{r}
#Load required libraries
library(SHIM)
library(dplyr)
library(hyenaR)
library(ggplot2)
library(spaMM)

## GENERATED IN STEP0_prepare_data/model_fit.Rmd
model_data <- readRDS(here::here("./analysis/data/model_data.RDS"))
```

```{r}
Kplot_data <- readRDS(here::here("./analysis/data/Kplot_data.RDS"))
```

```{r}
folder_name <- here::here("./STEP1_estimate_K/elasticity_oddsratio")
all_folders <- list.dirs(folder_name, recursive = FALSE)

all_variables <- purrr::map_df(.x = all_folders,
                               .f = function(parent_folder){
                                 
                                 print(paste0("Extracting: ", basename(parent_folder)))
                                 
                                 ## EXTRACT ESTIMATED K
                                 years <- start_year:end_year
                                 
                                 #Identify folders for high and low (names can differ by effect)
                                 child_folders <- list.dirs(parent_folder, recursive = FALSE)
                                 
                                 #Remove cases where we adjusted rank (separate)
                                 child_folders <- child_folders[grepl(child_folders, pattern = "higher|lower")]
                                 
                                 pb_yr <- progress::progress_bar$new(total = length(years)*length(child_folders))
                                 
                                 high_and_low <- purrr::map_df(.x = child_folders,
                                                               .f = function(target_folder, years){
                                                                 
                                                                 Kplot_data <- purrr::map_df(.x = years,
                                                                                             .f = function(year, folder_name){
                                                                                               
                                                                                               pb_yr$tick()
                                                                                               
                                                                                               txt_files <- list.files(paste0(folder_name, "/", year),
                                                                                                                       pattern = ".txt", full.names = TRUE)
                                                                                               
                                                                                               allsims <- purrr::map_df(.x = txt_files,
                                                                                                                        .f = function(filepath){
                                                                                                                          
                                                                                                                          readr::read_delim(filepath, show_col_types = FALSE, lazy = FALSE) %>%
                                                                                                                            dplyr::mutate(sim = stringr::str_extract(filepath, "(?<=_)[0-9]+(?=.txt)"))
                                                                                                                          
                                                                                                                        })
                                                                                               
                                                                                               estK <- allsims %>% 
                                                                                                 dplyr::group_by(.data$sim) %>% 
                                                                                                 dplyr::mutate(start_pop = first(pop_size)) %>% 
                                                                                                 dplyr::slice(ceiling(dplyr::n()/2):dplyr::n()) %>% 
                                                                                                 dplyr::summarise(K = median(.data$pop_size),
                                                                                                                  start_size = first(start_pop))
                                                                                               
                                                                                               plot_data <- estK %>% 
                                                                                                 dplyr::summarise(year = year,
                                                                                                                  globalK = median(.data$K),
                                                                                                                  lower = min(.data$K),
                                                                                                                  upper = max(.data$K),
                                                                                                                  points = list(data.frame(pop_size = .data$K,
                                                                                                                                           start_pop = .data$start_size)),
                                                                                                                  folder = basename(folder_name))
                                                                                               
                                                                                               return(plot_data)
                                                                                               
                                                                                             }, folder_name = target_folder)
                                                               }, years = years) |> 
                                   dplyr::mutate(VR = basename(parent_folder))
                                 
                                 high_and_low
                                 
                               })
```

## Plot

We don't need to do actual sensitivity because we adjusted everything by the same odds ratio (i.e. the denominator is always identical). So instead we can just report change in K (deltaK or absolute K?)

Join datasets

```{r}
sensitivity_data <- all_variables |> 
  rename(globalK_sens = globalK,
         lower_sens = lower,
         upper_sens = upper,
         points_sens = points)
  
```

```{r}
plot_data <- left_join(Kplot_data, sensitivity_data, by = c("year"), multiple = "all") |> 
  mutate(deltalogK = abs(log(globalK_sens) - log(globalK)), ## Change in K on log scale
         deltaK = abs(globalK_sens - globalK), ## Change in K on absolute scale
         ) |> 
  group_by(year, VR) |> 
  summarise(across(deltalogK:deltaK, .fns = ~data.frame(min = min(.),
                                                        max = max(.),
                                                        mean = mean(.))))
```

Adjust factor of VR to be in right order and have better names

```{r}
library(forcats)

plot_data <- plot_data |> 
  mutate(VR_full = factor(VR),
         VR_full = forcats::fct_relevel(VR_full,
                                        "femsurv", "preM", "postM",
                                        "primi", "nonprimi", "twin"),
         VR_full = forcats::fct_recode(VR_full,
                                       `Female survival` = "femsurv",
                                       `Male survival\n (juvenile)` = "preM",
                                       `Male survival\n (adult)` = "postM",
                                       `Reproduction\n(primiparous)` = "primi",
                                       `Reproduction\n(non-primiparous)` = "nonprimi",
                                       `Twinning` = "twin"))

ylim = c(0, max(plot_data$deltaK$mean) + 20)
  
```

```{r}
ggplot() +
  geom_errorbar(data = plot_data,
              aes(x = year, ymin = deltaK$min, ymax = deltaK$max),
              width = 0.25) +
  geom_point(data = plot_data,
            aes(x = year, y = deltaK$mean),
            size = 0.75) +
  geom_hline(yintercept = 0) +
  coord_cartesian(clip = "off",
                  expand = FALSE,
                  ylim = ylim,
                  xlim = c(1995, 2022)) +
  scale_y_continuous(breaks = seq(0, 300, 50)) +
  annotate(geom = "segment",
           y = 0, yend = -20,
           x = seq(1995, 2020, by = 5),
           xend = seq(1995, 2020, by = 5),
           lineend = "round", linejoin = "round") +
  annotate(geom = "segment",
           y = 0, yend = -10,
           x = seq(1995, 2022, by = 1),
           xend = seq(1995, 2022, by = 1),
           lineend = "round", linejoin = "round") +
  facet_wrap(facets = ~VR_full) +
  scale_colour_discrete(guide = NULL) +
  labs(x = "",
       y = "Change in time-varying\ncarrying capacity") +
  theme_classic() +
  theme(axis.text = element_text(colour = "black"),
        axis.text.x = element_text(margin = margin(t = 7)),
        axis.line.x = element_blank(),
        strip.text = element_text(colour = "black"),
        strip.background = element_rect(linewidth = 0.5),
        panel.spacing = unit(5, units = "mm"),
        plot.margin = margin(r = 5, l = 5, b = 5, t = 5))

ggsave(filename = here::here("./STEP3_supplementary_analysis/SX_elasticity/plots/supp_elasticity_plot_oddsratio_absK_new.png"), dpi = 600,
       width = 8, height = 5)
```


